name: Robot Framework Tests and Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-jsonlibrary
          pip install robotframework-jsonvalidator

      - name: Run tests with Robot Framework
        run: |
          robot --outputdir results LoginScenarios.robot
        continue-on-error: true

      - name: Upload Robot Framework report
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: results/report.html
        continue-on-error: true

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: results

      - name: Deploy Robot Framework report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_TOKEN_ROBOT }}
          publish_dir: ./results
          user_name: 'Pedro Thomé'
          user_email: 'pedro.th.dev@gmail.com'
