name: Robot Framework Tests and Deploy to GitHub Pages

on:
  push:
    branches:
      - main 
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-requests robotframework-jsonlibrary robotframework-jsonvalidator allure-robotframework 

      - name: Run tests with Robot Framework
        run: |
          robot --outputdir allure-results --listener allure_robotframework:allure-results LoginScenarios.robot
          ls -lah allure-results || echo "⚠️ No Allure results found!"
        continue-on-error: true

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure
        run: |
          curl -o allure-commandline.zip -L "https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.9/allure-commandline-2.13.9.zip"
          unzip -o allure-commandline.zip -d allure
          export PATH=$PATH:$PWD/allure/allure-2.13.9/bin

      - name: Generate Allure Report
        run: |
          mkdir -p allure-results/history
          cp -r allure-report/history allure-results/ 2>/dev/null || true
          allure generate allure-results --clean -o allure-report
        continue-on-error: true

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: true
        continue-on-error: true
