name: Robot Framework Tests and Deploy to GitHub Pages

on:
  push:
    branches:
      - main 
  workflow_dispatch:

permissions:
  contents: write  # Permissão necessária para publicar no GitHub Pages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-jsonlibrary
          pip install robotframework-jsonvalidator

      - name: Run tests with Robot Framework
        run: |
          robot --outputdir results LoginScenarios.robot
        continue-on-error: true

      - name: Upload Robot Framework report
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: results/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: always()  # Faz o deploy mesmo se os testes falharem

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Robot Framework report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN ou um PAT
          publish_dir: ./results
          